name = "keyring-be"
main = "src/index.ts"
compatibility_date = "2025-03-01"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "SessionDurableObject" ]

[[migrations]]
tag = "v2"
deleted_classes = [ "SessionDurableObject" ]

[[d1_databases]]
binding = "DB"
database_name = "keyring-db"
database_id = "dc4cfae2-3ab9-4def-8f03-1dda78e3abe2" # Placeholder

[vars]
NODE_ENV = "production"
ALLOWED_ORIGINS = "https://keyring.biyeon.store"
